/**:
  ros__parameters:
    min_longitudinal_offset: 6.93
    max_longitudinal_offset: 7.31
    min_lateral_offset: -3.12
    max_lateral_offset: 3.49
    min_height_offset: 4.23
    max_height_offset: 5.03
