/**:
  ros__parameters:
    wheel_radius: 2.878 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.845 # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 5.341 # between front wheel center and rear wheel center
    wheel_tread:  5.675 # between left wheel center and right wheel center
    front_overhang: 2.829 # between front wheel center and vehicle front
    rear_overhang: 3.200 # between rear wheel center and vehicle rear
    left_overhang: 0.655 # between left wheel center and vehicle left
    right_overhang: 0.655 # between right wheel center and vehicle right
    vehicle_height: 6.316
    max_steer_angle: 0.785 # [rad]
